name: Build and Deploy Vite App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: statuspage
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - name: Create .env file
        run: |
          echo "VITE_GraphQLAPI=${{ secrets.VITE_GraphQLAPI }}" >> .env
          echo "VITE_GraphQLAPIKey=${{ secrets.VITE_GraphQLAPIKey }}" >> .env
          echo "VITE_GraphQLAPIRegion=${{ secrets.VITE_GraphQLAPIRegion }}" >> .env
          echo "VITE_SatisfactoryDNS=${{ secrets.VITE_SatisfactoryDNS }}" >> .env
          echo "VITE_APP_PASSWORD=${{ secrets.VITE_APP_PASSWORD }}" >> .env
        working-directory: statuspage
      - run: pnpm build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/ --delete
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} 
